version: 2

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - restore_cache:
                name: Restore yarn cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}

            - run:
                name: Install dependencies
                command: yarn

            - save_cache:
                name: Save yarn packages to cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn

            - run:
                name: Run CI
                command: yarn ci:pipelines
